### ISSUE TITLE
Unhelpful error message when one commodity fails validation in v2 schema

### ISSUE THREAD

**Issue by Duke-Jones** [jamesremuscat/EDDN#26]
Hi there.

at the moment I try to send with the v2 schema (RegulatedNoise) but I've got some trouble 
and I don't know, whats wrong. Maybe someone see the reason for the error...

I get follwing answer:
&quot;FAIL: [&lt;ValidationError: &quot;{'name': 'Biowaste', 'supply': 23731, 'supplyLevel': 'Med', 'buyPrice': 17, 'demand': 0, 'sellPrice': 13, 'demandLevel': u''} is not valid under any of the given schemas&quot;&gt;]&quot;

this is the send string (I changed "http" to "h__p" to avoid viewing problems):

{&quot;header&quot;:{&quot;softwareVersion&quot;:&quot;1.84_0.26&quot;,&quot;gatewayTimestamp&quot;:&quot;2015-06-20T16:28:17+02:00&quot;,&quot;softwareName&quot;:&quot;RegulatedNoise__DJ&quot;,&quot;uploaderID&quot;:&quot;Duke Jones -_[Bla]_-&quot;},&quot;$schemaRef&quot;:&quot;h__p://schemas.elite-markets.net/eddn/commodity/2/test&quot;,&quot;message&quot;:{&quot;commodities&quot;:[{&quot;name&quot;:&quot;Biowaste&quot;,&quot;buyPrice&quot;:17,&quot;supplyLevel&quot;:&quot;Med&quot;,&quot;supply&quot;:23731,&quot;demand&quot;:0,&quot;sellPrice&quot;:13,&quot;demandLevel&quot;:&quot;&quot;},{&quot;name&quot;:&quot;Container Mit Sap 8-Kern&quot;,&quot;buyPrice&quot;:0,&quot;supplyLevel&quot;:&quot;&quot;,&quot;supply&quot;:0,&quot;demand&quot;:104480,&quot;sellPrice&quot;:60252,&quot;demandLevel&quot;:&quot;High&quot;},{&quot;name&quot;:&quot;Hydrogen Fuel&quot;,&quot;buyPrice&quot;:106,&quot;supplyLevel&quot;:&quot;Med&quot;,&quot;supply&quot;:407000,&quot;demand&quot;:0,&quot;sellPrice&quot;:101,&quot;demandLevel&quot;:&quot;&quot;},{&quot;name&quot;:&quot;Domestic Appliances&quot;,&quot;buyPrice&quot;:0,&quot;supplyLevel&quot;:&quot;&quot;,&quot;supply&quot;:0,&quot;demand&quot;:8437,&quot;sellPrice&quot;:530,&quot;demandLevel&quot;:&quot;Low&quot;},{&quot;name&quot;:&quot;Clothing&quot;,&quot;buyPrice&quot;:0,&quot;supplyLevel&quot;:&quot;&quot;,&quot;supply&quot;:0,&quot;demand&quot;:75284,&quot;sellPrice&quot;:348,&quot;demandLevel&quot;:&quot;Med&quot;},{&quot;name&quot;:&quot;Tauri Chimes&quot;,&quot;buyPrice&quot;:924,&quot;supplyLevel&quot;:&quot;High&quot;,&quot;supply&quot;:11,&quot;demand&quot;:0,&quot;sellPrice&quot;:924,&quot;demandLevel&quot;:&quot;&quot;},{&quot;name&quot;:&quot;Consumer Technology&quot;,&quot;buyPrice&quot;:0,&quot;supplyLeve<br/>l&quot;:&quot;&quot;,&quot;supply&quot;:0,&quot;demand&quot;:15777,&quot;sellPrice&quot;:7442,&quot;demandLevel&quot;:&quot;Med&quot;},{&quot;name&quot;:&quot;Beer&quot;,&quot;buyPrice&quot;:0,&quot;supplyLevel&quot;:&quot;&quot;,&quot;supply&quot;:0,&quot;demand&quot;:171223,&quot;sellPrice&quot;:283,&quot;demandLevel&quot;:&quot;Med&quot;},{&quot;name&quot;:&quot;Liquor&quot;,&quot;buyPrice&quot;:0,&quot;supplyLevel&quot;:&quot;&quot;,&quot;supply&quot;:0,&quot;demand&quot;:17813,&quot;sellPrice&quot;:825,&quot;demandLevel&quot;:&quot;Med&quot;},{&quot;name&quot;:&quot;Tobacco&quot;,&quot;buyPrice&quot;:0,&quot;supplyLevel&quot;:&quot;&quot;,&quot;supply&quot;:0,&quot;demand&quot;:11548,&quot;sellPrice&quot;:5006,&quot;demandLevel&quot;:&quot;Med&quot;},{&quot;name&quot;:&quot;Wine&quot;,&quot;buyPrice&quot;:0,&quot;supplyLevel&quot;:&quot;&quot;,&quot;supply&quot;:0,&quot;demand&quot;:151201,&quot;sellPrice&quot;:376,&quot;demandLevel&quot;:&quot;Med&quot;},{&quot;name&quot;:&quot;Power Generators&quot;,&quot;buyPrice&quot;:0,&quot;supplyLevel&quot;:&quot;&quot;,&quot;supply&quot;:0,&quot;demand&quot;:1427,&quot;sellPrice&quot;:530,&quot;demandLevel&quot;:&quot;Low&quot;}],&quot;timestamp&quot;:&quot;2015-06-20T16:28:17+02:00&quot;,&quot;systemName&quot;:&quot;39 Tauri&quot;,&quot;stationName&quot;:&quot;Porta&quot;}}

**Comment by Duke-Jones** [comment]
ok, forget it. I removed the empty demand and supply levels and now it's working.

**Comment by jamesremuscat** [comment]
That's a rubbish error message though. Reopening to see what can be done about that.

**Comment by bgol** [comment]
I tried to add the "id" entry for the commodities, but as soon as I do that the request failed with status 400:

```
Posting prices to EDDN...
{
    "$schemaRef": "http://schemas.elite-markets.net/eddn/commodity/2/test",
    "header": {
        "softwareName": "EDAPI Trade Dangerous Plugin",
        "softwareVersion": "3.6.3",
        "uploaderID": "Gazelle"
    },
    "message": {
        "commodities": [
            {
                "buyPrice": 0,
                "demand": 2403,
                "demandLevel": "Low",
                "id": 128049204,
                "name": "Explosives",
                "sellPrice": 300,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 90,
                "demand": 1,
                "demandLevel": "Low",
                "id": 128049202,
                "name": "Hydrogen Fuel",
                "sellPrice": 86,
                "supply": 79619,
                "supplyLevel": "Med"
            },
            {
                "buyPrice": 0,
                "demand": 206,
                "demandLevel": "Low",
                "id": 128049166,
                "name": "Water",
                "sellPrice": 124,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 3958,
                "demandLevel": "Low",
                "id": 128049241,
                "name": "Clothing",
                "sellPrice": 315,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 232,
                "demandLevel": "Low",
                "id": 128049240,
                "name": "Consumer Technology",
                "sellPrice": 6561,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 485,
                "demandLevel": "Low",
                "id": 128049238,
                "name": "Domestic Appliances",
                "sellPrice": 527,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 195,
                "demandLevel": "Low",
                "id": 128049182,
                "name": "Animal Meat",
                "sellPrice": 1286,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 150,
                "demandLevel": "Low",
                "id": 128049189,
                "name": "Coffee",
                "sellPrice": 1286,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 699,
                "demandLevel": "Low",
                "id": 128049183,
                "name": "Fish",
                "sellPrice": 403,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 366,
                "demandLevel": "Low",
                "id": 128049184,
                "name": "Food Cartridges",
                "sellPrice": 141,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 545,
                "demandLevel": "Low",
                "id": 128049178,
                "name": "Fruit And Vegetables",
                "sellPrice": 315,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 1947,
                "demandLevel": "Low",
                "id": 128049180,
                "name": "Grain",
                "sellPrice": 207,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 354,
                "demandLevel": "Low",
                "id": 128049185,
                "name": "Synthetic Meat",
                "sellPrice": 252,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 196,
                "demandLevel": "Low",
                "id": 128049188,
                "name": "Tea",
                "sellPrice": 1459,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 12468,
                "demandLevel": "Low",
                "id": 128049221,
                "name": "Mineral Extractors",
                "sellPrice": 844,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 274,
                "demandLevel": "Low",
                "id": 128049217,
                "name": "Power Generators",
                "sellPrice": 527,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 487,
                "demandLevel": "Low",
                "id": 128049218,
                "name": "Water Purifiers",
                "sellPrice": 300,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 360,
                "demandLevel": "Low",
                "id": 128682046,
                "name": "Advanced Medicines",
                "sellPrice": 2272,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 331,
                "demandLevel": "Low",
                "id": 128049210,
                "name": "Basic Medicines",
                "sellPrice": 315,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 292,
                "demandLevel": "Low",
                "id": 128049209,
                "name": "Performance Enhancers",
                "sellPrice": 6561,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 471,
                "demand": 1,
                "demandLevel": "Low",
                "id": 128049162,
                "name": "Cobalt",
                "sellPrice": 449,
                "supply": 41769,
                "supplyLevel": "Med"
            },
            {
                "buyPrice": 8739,
                "demand": 1,
                "demandLevel": "Low",
                "id": 128049154,
                "name": "Gold",
                "sellPrice": 8603,
                "supply": 7533,
                "supplyLevel": "Med"
            },
            {
                "buyPrice": 12551,
                "demand": 1,
                "demandLevel": "Low",
                "id": 128049153,
                "name": "Palladium",
                "sellPrice": 12489,
                "supply": 1075,
                "supplyLevel": "Med"
            },
            {
                "buyPrice": 4163,
                "demand": 1,
                "demandLevel": "Low",
                "id": 128049155,
                "name": "Silver",
                "sellPrice": 4096,
                "supply": 23143,
                "supplyLevel": "Med"
            },
            {
                "buyPrice": 41,
                "demand": 1,
                "demandLevel": "Low",
                "id": 128049165,
                "name": "Bauxite",
                "sellPrice": 34,
                "supply": 245424,
                "supplyLevel": "Med"
            },
            {
                "buyPrice": 1999,
                "demand": 1,
                "demandLevel": "Low",
                "id": 128049156,
                "name": "Bertrandite",
                "sellPrice": 1966,
                "supply": 14896,
                "supplyLevel": "Med"
            },
            {
                "buyPrice": 1037,
                "demand": 1,
                "demandLevel": "Low",
                "id": 128049159,
                "name": "Coltan",
                "sellPrice": 1006,
                "supply": 24515,
                "supplyLevel": "Med"
            },
            {
                "buyPrice": 1495,
                "demand": 1,
                "demandLevel": "Low",
                "id": 128049158,
                "name": "Gallite",
                "sellPrice": 1452,
                "supply": 38007,
                "supplyLevel": "Med"
            },
            {
                "buyPrice": 1728,
                "demand": 1,
                "demandLevel": "Low",
                "id": 128049157,
                "name": "Indite",
                "sellPrice": 1678,
                "supply": 16967,
                "supplyLevel": "Med"
            },
            {
                "buyPrice": 376,
                "demand": 1,
                "demandLevel": "Low",
                "id": 128049161,
                "name": "Lepidolite",
                "sellPrice": 358,
                "supply": 49952,
                "supplyLevel": "Med"
            },
            {
                "buyPrice": 0,
                "demand": 376,
                "demandLevel": "High",
                "id": 128673848,
                "name": "Low Temperature Diamonds",
                "sellPrice": 69265,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 176,
                "demand": 1,
                "demandLevel": "Low",
                "id": 128049163,
                "name": "Rutile",
                "sellPrice": 164,
                "supply": 85506,
                "supplyLevel": "Med"
            },
            {
                "buyPrice": 629,
                "demand": 1,
                "demandLevel": "Low",
                "id": 128049160,
                "name": "Uraninite",
                "sellPrice": 609,
                "supply": 34981,
                "supplyLevel": "Med"
            },
            {
                "buyPrice": 0,
                "demand": 2086,
                "demandLevel": "Low",
                "id": 128049214,
                "name": "Beer",
                "sellPrice": 175,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 1272,
                "demandLevel": "High",
                "id": 128672306,
                "name": "Bootleg Liquor",
                "sellPrice": 678,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 2094,
                "demandLevel": "Low",
                "id": 128049216,
                "name": "Liquor",
                "sellPrice": 641,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 674,
                "demandLevel": "Low",
                "id": 128049215,
                "name": "Wine",
                "sellPrice": 252,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 69799,
                "demandLevel": "Low",
                "id": 128049672,
                "name": "Bioreducing Lichen",
                "sellPrice": 951,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 85770,
                "demandLevel": "Med",
                "id": 128049226,
                "name": "H.E. Suits",
                "sellPrice": 357,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 10,
                "demand": 1,
                "demandLevel": "Low",
                "id": 128049244,
                "name": "Biowaste",
                "sellPrice": 8,
                "supply": 8565,
                "supplyLevel": "Med"
            },
            {
                "buyPrice": 0,
                "demand": 119,
                "demandLevel": "Low",
                "id": 128049236,
                "name": "Non-Lethal Weapons",
                "sellPrice": 1766,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 519,
                "demandLevel": "Low",
                "id": 128049233,
                "name": "Personal Weapons",
                "sellPrice": 4122,
                "supply": 0,
                "supplyLevel": "Low"
            },
            {
                "buyPrice": 0,
                "demand": 119,
                "demandLevel": "Low",
                "id": 128049235,
                "name": "Reactive Armour",
                "sellPrice": 2008,
                "supply": 0,
                "supplyLevel": "Low"
            }
        ],
        "stationName": "Tokubei Port",
        "systemName": "Caelinus",
        "timestamp": "2016-07-01T14:22:24.483030+02:00"
    }
}
Traceback (most recent call last):
  File "./trade.py", line 104, in <module>
    main(sys.argv)
  File "./trade.py", line 77, in main
    results = cmdenv.run(tdb)
  File "d:\OpenSource\tradedangerous\commands\commandenv.py", line 80, in run
    return self._cmd.run(results, self, tdb)
  File "d:\OpenSource\tradedangerous\commands\import_cmd.py", line 124, in run
    if not plugin.run():
  File "d:\OpenSource\tradedangerous\plugins\edapi_plug.py", line 4127, in run
    eddn_market
  File "d:\OpenSource\tradedangerous\plugins\edapi_plug.py", line 3708, in publishCommodities
    self.postMessage(message, timestamp)
  File "d:\OpenSource\tradedangerous\plugins\edapi_plug.py", line 3683, in postMessage
    r.raise_for_status()
  File "c:\Python34\lib\site-packages\requests\models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://eddn-gateway.elite-markets.net:8080/upload/

```

**Comment by AnthorNet** [comment]
The ID field is not in production yet
